[2022-07-29 21:02:00,193] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dataperf.list manual__2022-07-29T21:01:59.151852+00:00 [queued]>
[2022-07-29 21:02:00,208] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dataperf.list manual__2022-07-29T21:01:59.151852+00:00 [queued]>
[2022-07-29 21:02:00,208] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-29 21:02:00,209] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-07-29 21:02:00,209] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-29 21:02:00,227] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): list> on 2022-07-29 21:01:59.151852+00:00
[2022-07-29 21:02:00,231] {standard_task_runner.py:52} INFO - Started process 109 to run task
[2022-07-29 21:02:00,234] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dataperf', 'list', 'manual__2022-07-29T21:01:59.151852+00:00', '--job-id', '209', '--raw', '--subdir', 'DAGS_FOLDER/dataperfr.py', '--cfg-path', '/tmp/tmpyx0jatua', '--error-file', '/tmp/tmp39jqcm_u']
[2022-07-29 21:02:00,234] {standard_task_runner.py:80} INFO - Job 209: Subtask list
[2022-07-29 21:02:00,295] {task_command.py:371} INFO - Running <TaskInstance: dataperf.list manual__2022-07-29T21:01:59.151852+00:00 [running]> on host bd7d42b52bee
[2022-07-29 21:02:00,372] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dataperf
AIRFLOW_CTX_TASK_ID=list
AIRFLOW_CTX_EXECUTION_DATE=2022-07-29T21:01:59.151852+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-29T21:01:59.151852+00:00
[2022-07-29 21:02:00,373] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-29 21:02:00,374] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'docker-compose run dataperf-debugging-submission']
[2022-07-29 21:02:00,384] {subprocess.py:85} INFO - Output:
[2022-07-29 21:02:00,386] {subprocess.py:92} INFO - bash: line 1: docker-compose: command not found
[2022-07-29 21:02:00,387] {subprocess.py:96} INFO - Command exited with return code 127
[2022-07-29 21:02:00,404] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-07-29 21:02:00,407] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=dataperf, task_id=list, execution_date=20220729T210159, start_date=20220729T210200, end_date=20220729T210200
[2022-07-29 21:02:00,420] {standard_task_runner.py:97} ERROR - Failed to execute job 209 for task list (Bash command failed. The command returned a non-zero exit code 127.; 109)
[2022-07-29 21:02:00,446] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-29 21:02:00,477] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
